//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int ID { get; set; }
        public string Kulladi { get; set; }
        public string Sifre { get; set; }
        public string Yetki { get; set; }
        public string Resim { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public virtual bool BeniHatirla { get; set; }
    }
}
