//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUyeler()
        {
            this.TBLCezalar = new HashSet<TBLCezalar>();
            this.TBLHareket = new HashSet<TBLHareket>();
        }
    
        public int UyeID { get; set; }
        public string UyeAd { get; set; }
        public string UyeSoyad { get; set; }
        public string UyeMail { get; set; }
        public string UyeKullaniciAdi { get; set; }
        public string UyeSifre { get; set; }
        public string UyeTelefon { get; set; }
        public string UyeOkul { get; set; }
        public string UyeFotograf { get; set; }
        public virtual bool Benihatirla { get; set; }   
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLCezalar> TBLCezalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHareket> TBLHareket { get; set; }
    }
}
